AllCops:
  DisplayCopNames: true
  # Proto files are generated automatically and there's not much we can do about them.
  Exclude:
    - "bin/*"
    - "config/environments/*"
    - "config/initializers/*"
    - "db/**/*"
    - "lib/tasks/*"
    - "spec/support/*"
    - "vendor/**/*"
  TargetRubyVersion: 2.6.2
  TargetRailsVersion: 5.2

Documentation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Exclude:
    - "spec/**/*"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Lint/UselessAssignment:
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
  Max: 30

Metrics/LineLength:
  Exclude:
    - "spec/**/*"
  Max: 120

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 130


Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Naming/MethodParameterName:
  MinNameLength: 2

Metrics/ParameterLists:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 8

Style/RaiseArgs:
  Enabled: false
